### ISSUE TITLE
Please fix snyk issue: with multer [fix is available]

### ISSUE THREAD

**Issue by harshagarwal00** [chanphiromsok/fastify-file-interceptor#1]
multer fix available with package version: 1.4.5-lts.1 to fix snyk
Details: https://github.com/expressjs/multer/pull/1097#issuecomment-1140395967

https://github.com/expressjs/multer/tree/v1.4.5-lts.1

**Comment by harshagarwal00** [comment]
Also use latest version of fastify-multer: 
https://www.npmjs.com/package/fastify-multer/v/2.0.3
[it has fixed the snyk vulnerability]

**Comment by harshagarwal00** [comment]
@chanphiromsok

**Comment by chanphiromsok** [comment]
thanks for your report i will upgrade soon

**Comment by harshagarwal00** [comment]
Hey @chanphiromsok : waiting for the fix...

**Comment by harshagarwal00** [comment]
hey @chanphiromsok : was curious by what date was a  release for this targetted?

**Comment by chanphiromsok** [comment]
sorry I have a tone of work now I just updated it on 1.0.7

**Comment by harshagarwal00** [comment]
thanks!
