### ISSUE TITLE
No matching version found for multer@1.4.5-lts.

### ISSUE THREAD

**Issue by leobel** [chanphiromsok/fastify-file-interceptor#3]
`npm install fastify-file-interceptor` is failing with: "No matching version found for multer@1.4.5-lts."

I'd take a look to dependencies and it has: 
`"multer": "1.4.5-lts",` but on npm I cannot find that exact version. [(Here)](https://www.npmjs.com/package/multer?activeTab=versions) the latest version is `1.4.5-lts.1` with a `.1` at the end, could be this a typo?

**Comment by some1awesome** [comment]
Having the same problem.  Reverting to 1.0.6 in the meantime since it doesn't have the same problem

**Comment by chanphiromsok** [comment]
I fill fixed it tonight sorry it's typo mistake

**Comment by chanphiromsok** [comment]
fixed typo library version
