### ISSUE TITLE
File in memory instead of saved to disk

### ISSUE THREAD

**Issue by Varagos** [chanphiromsok/fastify-file-interceptor#4]
Is there any example with a controller that does not store automatically the file somewhere, but instead keeps it in memory (attached to the request for example) ?

**Comment by chanphiromsok** [comment]
> Is there any example with a controller that does not store automatically the file somewhere, but instead keeps it in memory (attached to the request for example) ?

I didn't add MemoryStorage to example and here is the refs doc

https://github.com/fox1t/fastify-multer#memorystorage 

this library is base on this one so I think it should work just replace diskStorage with your memory storage

**Comment by chanphiromsok** [comment]
> Is there any example with a controller that does not store automatically the file somewhere, but instead keeps it in memory (attached to the request for example) ?

I think issue can close now 😅. Happy coding
