### ISSUE TITLE
License

### ISSUE THREAD

**Issue by armsnyder** [chanphiromsok/fastify-file-interceptor#8]
Hi, could you consider adding a license to the git repository or package.json? Without one we cannot legally use this software. Thanks.

**Comment by chanphiromsok** [comment]
Hi I will add it but first of all, I don't familiar with licence at all and my purpose everyone feel free to use this package

**Comment by armsnyder** [comment]
Hi @chanphiromsok, thanks for the reply. If you are okay with any use of the package, the MIT and Apache-2.0 licenses are both popular and most easy for package users to comply with.

**Comment by chanphiromsok** [comment]
> Hi @chanphiromsok, thanks for the reply. If you are okay with any use of the package, the MIT and Apache-2.0 licenses are both popular and most easy for package users to comply with.

I will check both of these which one is suite the user need
